"""CMiC stream schemas copied from the hotglue connector definition."""

from __future__ import annotations

PROJECTS_SCHEMA = {
    "type": "object",
    "properties": {
        "hg_modified_at": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpAddContactName": {"type": ["string", "null"]},
        "GrpmpAddLine1": {"type": ["string", "null"]},
        "GrpmpAddLine2": {"type": ["string", "null"]},
        "GrpmpAddLine3": {"type": ["string", "null"]},
        "GrpmpAgendaItemIdMask": {"type": ["string", "null"]},
        "GrpmpArchitectName": {"type": ["string", "null"]},
        "GrpmpAutoCalcMarkupFlag": {"type": ["string", "null"]},
        "GrpmpBallInCourtReportFlg": {"type": ["string", "null"]},
        "GrpmpBidDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpBidJobCode": {"type": ["string", "null"]},
        "GrpmpBidJobDeptCode": {"type": ["string", "null"]},
        "GrpmpBidJobDeptName": {"type": ["string", "null"]},
        "GrpmpBidJobName": {"type": ["string", "null"]},
        "GrpmpBidMask": {"type": ["string", "null"]},
        "GrpmpBidMaskOverride": {"type": ["string", "null"]},
        "GrpmpBidMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpBidWonLostDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpCalcIssueDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpCalcOcoDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpCalcPmntcDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpCalcPmplDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpCalcRfiDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpCalcSbmtDtOnWrkdys": {"type": ["string", "null"]},
        "GrpmpClosedDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpClvValueCode1": {"type": ["string", "null"]},
        "GrpmpClvValueCode2": {"type": ["string", "null"]},
        "GrpmpClvValueCode3": {"type": ["string", "null"]},
        "GrpmpClvValueCode4": {"type": ["string", "null"]},
        "GrpmpClvValueCode5": {"type": ["string", "null"]},
        "GrpmpClvValueCode6": {"type": ["string", "null"]},
        "GrpmpCollabUrl": {"type": ["string", "null"]},
        "GrpmpCommlgMask": {"type": ["string", "null"]},
        "GrpmpCommlgMaskOverride": {"type": ["string", "null"]},
        "GrpmpCommlgMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpCompCode": {"type": ["string", "null"]},
        "GrpmpCompName": {"type": ["string", "null"]},
        "GrpmpCorrAdd1": {"type": ["string", "null"]},
        "GrpmpCorrAdd2": {"type": ["string", "null"]},
        "GrpmpCorrAdd3": {"type": ["string", "null"]},
        "GrpmpCorrAddContactName": {"type": ["string", "null"]},
        "GrpmpCorrCountry": {"type": ["string", "null"]},
        "GrpmpCorrPostalCode": {"type": ["string", "null"]},
        "GrpmpCorrRegionCode": {"type": ["string", "null"]},
        "GrpmpCorrespondenceAddrCode": {"type": ["string", "null"]},
        "GrpmpCountry": {"type": ["string", "null"]},
        "GrpmpCreateJobFlag": {"type": ["string", "null"]},
        "GrpmpCurrContAmt": {"type": ["number", "null"]},
        "GrpmpCustAdd1": {"type": ["string", "null"]},
        "GrpmpCustAdd2": {"type": ["string", "null"]},
        "GrpmpCustAdd3": {"type": ["string", "null"]},
        "GrpmpCustAddCode": {"type": ["string", "null"]},
        "GrpmpCustAddContactName": {"type": ["string", "null"]},
        "GrpmpCustCode": {"type": ["string", "null"]},
        "GrpmpCustCountry": {"type": ["string", "null"]},
        "GrpmpCustName": {"type": ["string", "null"]},
        "GrpmpCustPostalCode": {"type": ["string", "null"]},
        "GrpmpCustRegionCode": {"type": ["string", "null"]},
        "GrpmpDayjrMask": {"type": ["string", "null"]},
        "GrpmpDayjrMaskOverride": {"type": ["string", "null"]},
        "GrpmpDayjrMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpDefaultBillTypeCode": {"type": ["string", "null"]},
        "GrpmpDefaultBillTypeName": {"type": ["string", "null"]},
        "GrpmpDefaultBilltoAddCode": {"type": ["string", "null"]},
        "GrpmpDefaultBilltoAddName": {"type": ["string", "null"]},
        "GrpmpDefaultBuyCode": {"type": ["string", "null"]},
        "GrpmpDefaultDeliveryPeriod": {"type": ["integer", "null"]},
        "GrpmpDefaultInvoiceFormat": {"type": ["string", "null"]},
        "GrpmpDefaultJbMapCode": {"type": ["string", "null"]},
        "GrpmpDefaultJbMapName": {"type": ["string", "null"]},
        "GrpmpDefaultJobBillMethod": {"type": ["string", "null"]},
        "GrpmpDefaultReqCode": {"type": ["string", "null"]},
        "GrpmpDefaultRfiPeriod": {"type": ["integer", "null"]},
        "GrpmpDefaultShiptoAddCode": {"type": ["string", "null"]},
        "GrpmpDefaultShiptoAddName": {"type": ["string", "null"]},
        "GrpmpDeptCode": {"type": ["string", "null"]},
        "GrpmpDeptName": {"type": ["string", "null"]},
        "GrpmpDfltCmdetailMode": {"type": ["string", "null"]},
        "GrpmpDfltDjAttachmentFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjGeneralFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjLabForceFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjMaterialsFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjNotesFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjOeOnJobFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjOwnEqpFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjOwnLabFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjSafetyFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjTasksFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjTlCompFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjTradeEqpFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjTradeLabFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjUnitcFlag": {"type": ["string", "null"]},
        "GrpmpDfltDjVisitorsFlag": {"type": ["string", "null"]},
        "GrpmpDfltInvoiceFormatNm": {"type": ["string", "null"]},
        "GrpmpDfltIssueRevPeriod": {"type": ["integer", "null"]},
        "GrpmpDfltLeadTimeStage1": {"type": ["number", "null"]},
        "GrpmpDfltLeadTimeStage2": {"type": ["number", "null"]},
        "GrpmpDfltLeadTimeStage3": {"type": ["number", "null"]},
        "GrpmpDfltLeadTimeStage4": {"type": ["number", "null"]},
        "GrpmpDfltLeadTimeStage5": {"type": ["number", "null"]},
        "GrpmpDfltLeadTimeStage6": {"type": ["number", "null"]},
        "GrpmpDfltMeetingFootnote": {"type": ["string", "null"]},
        "GrpmpDfltPlistComplPeriod": {"type": ["integer", "null"]},
        "GrpmpDfltPmntcRevPeriod": {"type": ["integer", "null"]},
        "GrpmpDfltRfiContactCode": {"type": ["string", "null"]},
        "GrpmpDfltRfiContactName": {"type": ["string", "null"]},
        "GrpmpDfltRfiPartnCode": {"type": ["string", "null"]},
        "GrpmpDfltRfiPartnTypeCode": {"type": ["string", "null"]},
        "GrpmpDfltRfqReviewDays": {"type": ["integer", "null"]},
        "GrpmpDfltSbmtContactCode": {"type": ["string", "null"]},
        "GrpmpDfltSbmtContactName": {"type": ["string", "null"]},
        "GrpmpDfltSbmtPartnCode": {"type": ["string", "null"]},
        "GrpmpDfltSbmtPtnTypeCode": {"type": ["string", "null"]},
        "GrpmpEndDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpEntryRfiAnsByFlag": {"type": ["string", "null"]},
        "GrpmpEntryRfiAnsDateFlag": {"type": ["string", "null"]},
        "GrpmpFaxNum": {"type": ["string", "null"]},
        "GrpmpFwdMask": {"type": ["string", "null"]},
        "GrpmpFwdMaskOverride": {"type": ["string", "null"]},
        "GrpmpFwdMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpHardBidFlag": {"type": ["string", "null"]},
        "GrpmpIssueIdMask": {"type": ["string", "null"]},
        "GrpmpIssueIdMaskOverride": {"type": ["string", "null"]},
        "GrpmpIssueIdMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpItbSenderEmail": {"type": ["string", "null"]},
        "GrpmpItbSenderName": {"type": ["string", "null"]},
        "GrpmpIuCreateDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpIuUpdateDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpJobAllowTransFlag": {"type": ["string", "null"]},
        "GrpmpJobBidFlag": {"type": ["string", "null"]},
        "GrpmpJobBillMethCode": {"type": ["string", "null"]},
        "GrpmpJobBillingTypeCode": {"type": ["string", "null"]},
        "GrpmpJobBillingTypeName": {"type": ["string", "null"]},
        "GrpmpJobCode": {"type": ["string", "null"]},
        "GrpmpJobCreationDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpJobDeptCode": {"type": ["string", "null"]},
        "GrpmpJobDeptName": {"type": ["string", "null"]},
        "GrpmpJobInvoiceFormatCode": {"type": ["string", "null"]},
        "GrpmpJobInvoiceFormatNm": {"type": ["string", "null"]},
        "GrpmpJobJbMapCode": {"type": ["string", "null"]},
        "GrpmpJobJbMapName": {"type": ["string", "null"]},
        "GrpmpJobName": {"type": ["string", "null"]},
        "GrpmpJobOrigBudgetEffDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpJobSecGroup": {"type": ["string", "null"]},
        "GrpmpJobStatusCode": {"type": ["string", "null"]},
        "GrpmpKeyWordDesc": {"type": ["string", "null"]},
        "GrpmpLienWaiverText": {"type": ["string", "null"]},
        "GrpmpManagerName": {"type": ["string", "null"]},
        "GrpmpMeetingIdMask": {"type": ["string", "null"]},
        "GrpmpMobileUrl": {"type": ["string", "null"]},
        "GrpmpNoticeMask": {"type": ["string", "null"]},
        "GrpmpNoticeMaskOverride": {"type": ["string", "null"]},
        "GrpmpNoticeMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpOcoOrigContAmtOvrd": {"type": ["string", "null"]},
        "GrpmpOrigContOverrideAmt": {"type": ["number", "null"]},
        "GrpmpPartnAbbrevInRfiId": {"type": ["string", "null"]},
        "GrpmpPartnAbbrevInTrnsmId": {"type": ["string", "null"]},
        "GrpmpPciUseScopeAmtFlag": {"type": ["string", "null"]},
        "GrpmpPhoneNum": {"type": ["string", "null"]},
        "GrpmpPmplMask": {"type": ["string", "null"]},
        "GrpmpPmplMaskOverride": {"type": ["string", "null"]},
        "GrpmpPmplMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpPmpliMask": {"type": ["string", "null"]},
        "GrpmpPmpliMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpPostalCode": {"type": ["string", "null"]},
        "GrpmpProjCode": {"type": ["string", "null"]},
        "GrpmpProjCtrlCode": {"type": ["string", "null"]},
        "GrpmpProjDescription": {"type": ["string", "null"]},
        "GrpmpProjEndDtUpdateable": {"type": ["string", "null"]},
        "GrpmpProjName": {"type": ["string", "null"]},
        "GrpmpProjPhotoUrl": {"type": ["string", "null"]},
        "GrpmpRegionCode": {"type": ["string", "null"]},
        "GrpmpRegionName": {"type": ["string", "null"]},
        "GrpmpRfiMask": {"type": ["string", "null"]},
        "GrpmpRfiMaskOverride": {"type": ["string", "null"]},
        "GrpmpRfiMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpRsschedVerCode": {"type": ["string", "null"]},
        "GrpmpRsschedVerName": {"type": ["string", "null"]},
        "GrpmpSbmtApprvContactCode": {"type": ["string", "null"]},
        "GrpmpSbmtApprvPartnCode": {"type": ["string", "null"]},
        "GrpmpSbmtApprvPtnTypeCode": {"type": ["string", "null"]},
        "GrpmpSbmtMask": {"type": ["string", "null"]},
        "GrpmpSbmtMaskOverride": {"type": ["string", "null"]},
        "GrpmpSbmtMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpSbmtpMask": {"type": ["string", "null"]},
        "GrpmpSbmtpMaskOverride": {"type": ["string", "null"]},
        "GrpmpSbmtpMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpStartDate": {"type": ["string", "null"], "format": "date-time"},
        "GrpmpStartPageUrl": {"type": ["string", "null"]},
        "GrpmpStatusCode": {"type": ["string", "null"]},
        "GrpmpSubcontractedVolumeAmt": {"type": ["number", "null"]},
        "GrpmpSuperintName": {"type": ["string", "null"]},
        "GrpmpTrnsmMask": {"type": ["string", "null"]},
        "GrpmpTrnsmMaskOverride": {"type": ["string", "null"]},
        "GrpmpTrnsmMaskSeqProj": {"type": ["string", "null"]},
        "GrpmpUseBidItemEaFlag": {"type": ["string", "null"]},
        "GrpmpVUuid": {"type": ["string", "null"]},
        "GrpmpWorkLocCode": {"type": ["string", "null"]},
        "GrpmpWorkLocName": {"type": ["string", "null"]},
        "links": {
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "rel": {"type": ["string", "null"]},
                    "href": {"type": ["string", "null"]},
                    "name": {"type": ["string", "null"]},
                    "kind": {"type": ["string", "null"]},
                },
            },
        },
    },
}

CONTRACTS_SCHEMA = {
    "type": "object",
    "properties": {
        "hg_modified_at": {"type": ["string", "null"], "format": "date-time"},
        "CChangeDesc": {"type": ["string", "null"]},
        "CNewRevisedDesc": {"type": ["string", "null"]},
        "COriginalDesc": {"type": ["string", "null"]},
        "CRecievedDesc": {"type": ["string", "null"]},
        "CTitle1": {"type": ["string", "null"]},
        "CTitle2": {"type": ["string", "null"]},
        "CTitle3": {"type": ["string", "null"]},
        "CTitle4": {"type": ["string", "null"]},
        "CUnpostedDesc": {"type": ["string", "null"]},
        "PartnTypeCode": {"type": ["string", "null"]},
        "PostOverrideFlag": {"type": ["string", "null"]},
        "ScmstAbbrevPartnCode": {"type": ["string", "null"]},
        "ScmstAcctDescription": {"type": ["string", "null"]},
        "ScmstActionCode": {"type": ["string", "null"]},
        "ScmstAltVenAddCode": {"type": ["string", "null"]},
        "ScmstAppCode": {"type": ["string", "null"]},
        "ScmstArAmt": {"type": ["number", "null"]},
        "ScmstBankAccount": {"type": ["string", "null"]},
        "ScmstBankDept": {"type": ["string", "null"]},
        "ScmstBillCode": {"type": ["string", "null"]},
        "ScmstCashAmt": {"type": ["number", "null"]},
        "ScmstCdiFlag": {"type": ["string", "null"]},
        "ScmstChgCode": {"type": ["string", "null"]},
        "ScmstChqHandleCode": {"type": ["string", "null"]},
        "ScmstCloseDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstClvValueCode1": {"type": ["string", "null"]},
        "ScmstClvValueCode2": {"type": ["string", "null"]},
        "ScmstClvValueCode3": {"type": ["string", "null"]},
        "ScmstClvValueCode4": {"type": ["string", "null"]},
        "ScmstClvValueCode5": {"type": ["string", "null"]},
        "ScmstClvValueCode6": {"type": ["string", "null"]},
        "ScmstCmBudrCode": {"type": ["string", "null"]},
        "ScmstCmChgCode": {"type": ["string", "null"]},
        "ScmstCmCompCode": {"type": ["string", "null"]},
        "ScmstCmJobCode": {"type": ["string", "null"]},
        "ScmstCompCode": {"type": ["string", "null"]},
        "ScmstComplFlag": {"type": ["string", "null"]},
        "ScmstContAmt": {"type": ["number", "null"]},
        "ScmstContCode": {"type": ["string", "null"]},
        "ScmstContType": {"type": ["string", "null"]},
        "ScmstContactCode": {"type": ["string", "null"]},
        "ScmstContactName": {"type": ["string", "null"]},
        "ScmstCorrespAddCode": {"type": ["string", "null"]},
        "ScmstCreateContOnFlyFlag": {"type": ["string", "null"]},
        "ScmstCurcFactorNum": {"type": ["number", "null"]},
        "ScmstCurrCode": {"type": ["string", "null"]},
        "ScmstCurrName": {"type": ["string", "null"]},
        "ScmstDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstDefaultTaxesFlag": {"type": ["string", "null"]},
        "ScmstDesc": {"type": ["string", "null"]},
        "ScmstDfltAmt": {"type": ["number", "null"]},
        "ScmstDfltCatCode": {"type": ["string", "null"]},
        "ScmstDfltPhsCode": {"type": ["string", "null"]},
        "ScmstDoNotExceedAmt": {"type": ["number", "null"]},
        "ScmstEndDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstExecutedDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstGcsPayRequestFlag": {"type": ["string", "null"]},
        "ScmstGstAmt": {"type": ["number", "null"]},
        "ScmstGstPc": {"type": ["number", "null"]},
        "ScmstHldbkPc": {"type": ["number", "null"]},
        "ScmstHldbkPcRule": {"type": ["string", "null"]},
        "ScmstHldbkRlsFromSc": {"type": ["string", "null"]},
        "ScmstHoldPaymentDays": {"type": ["integer", "null"]},
        "ScmstHoldPaymentFlag": {"type": ["string", "null"]},
        "ScmstImpactDays": {"type": ["integer", "null"]},
        "ScmstInvEntryState": {"type": ["string", "null"]},
        "ScmstInvHldbkTaxFlag": {"type": ["string", "null"]},
        "ScmstIssuedDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstIuCreateDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstIuUpdateDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstJobCode": {"type": ["string", "null"]},
        "ScmstJobCtrlCode": {"type": ["string", "null"]},
        "ScmstMainChgCode": {"type": ["string", "null"]},
        "ScmstMainContCode": {"type": ["string", "null"]},
        "ScmstMainVenCode": {"type": ["string", "null"]},
        "ScmstName": {"type": ["string", "null"]},
        "ScmstNonCreditInclTaxAmt": {"type": ["number", "null"]},
        "ScmstNonCreditTaxAmt": {"type": ["number", "null"]},
        "ScmstOrigBidpAmt": {"type": ["number", "null"]},
        "ScmstOrigBidpOraseq": {"type": ["number", "null"]},
        "ScmstOvrrideNotExceedFlag": {"type": ["string", "null"]},
        "ScmstOverrideFlag": {"type": ["string", "null"]},
        "ScmstPbContCode": {"type": ["string", "null"]},
        "ScmstPbCustCode": {"type": ["string", "null"]},
        "ScmstPostBatch": {"type": ["number", "null"]},
        "ScmstPostDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstPreferedQuoteFlag": {"type": ["string", "null"]},
        "ScmstPrintedCoFlag": {"type": ["string", "null"]},
        "ScmstProjOraseq": {"type": ["number", "null"]},
        "ScmstRating": {"type": ["number", "null"]},
        "ScmstRctReferenceNum": {"type": ["string", "null"]},
        "ScmstReceivedDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstRecipientEmail": {"type": ["string", "null"]},
        "ScmstRevBatch": {"type": ["number", "null"]},
        "ScmstRevDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstScControlAmt": {"type": ["number", "null"]},
        "ScmstSchedExistsFlag": {"type": ["string", "null"]},
        "ScmstScheduleFlag": {"type": ["string", "null"]},
        "ScmstScopeDesc": {"type": ["string", "null"]},
        "ScmstScschLastSeqNumUsed": {"type": ["number", "null"]},
        "ScmstSelfBilledFlag": {"type": ["string", "null"]},
        "ScmstSenderEmail": {"type": ["string", "null"]},
        "ScmstSepVouPerJobFlag": {"type": ["string", "null"]},
        "ScmstSrcCode": {"type": ["string", "null"]},
        "ScmstStartDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstStatCode": {"type": ["string", "null"]},
        "ScmstStatusCode": {"type": ["string", "null"]},
        "ScmstSubcontrCode": {"type": ["string", "null"]},
        "ScmstSubcontractorChgCode": {"type": ["string", "null"]},
        "ScmstTax1Code": {"type": ["string", "null"]},
        "ScmstTax2Code": {"type": ["string", "null"]},
        "ScmstTax3Code": {"type": ["string", "null"]},
        "ScmstTermCode": {"type": ["string", "null"]},
        "ScmstTermName": {"type": ["string", "null"]},
        "ScmstTexturaFlag": {"type": ["string", "null"]},
        "ScmstUser": {"type": ["string", "null"]},
        "ScmstUserPrvlgFlag": {"type": ["string", "null"]},
        "ScmstVenCode": {"type": ["string", "null"]},
        "ScmstVenName": {"type": ["string", "null"]},
        "ScmstVUuid": {"type": ["string", "null"]},
        "ScmstDepositAmt": {"type": ["number", "null"]},
        "ScmstDepositApprovalDate": {"type": ["string", "null"], "format": "date-time"},
        "ScmstDepositPct": {"type": ["number", "null"]},
        "ScmstWorkflowStatus": {"type": ["string", "null"]},
        "ScmstDateTimePost": {"type": ["string", "null"], "format": "date-time"},
        "ScmstPost": {"type": ["string", "null"]},
        "links": {
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "rel": {"type": ["string", "null"]},
                    "href": {"type": ["string", "null"]},
                    "name": {"type": ["string", "null"]},
                    "kind": {"type": ["string", "null"]},
                },
            },
        },
    },
}

VENDORS_SCHEMA = {
    "type": "object",
    "properties": {
        "hg_modified_at": {"type": ["string", "null"], "format": "date-time"},
        "BpvenCompCode": {"type": ["string", "null"]},
        "BpvenCompName": {"type": ["string", "null"]},
        "BpvenBpCode": {"type": ["string", "null"]},
        "BpvenBpName": {"type": ["string", "null"]},
        "BpvenPayAdd1": {"type": ["string", "null"]},
        "BpvenPayAdd2": {"type": ["string", "null"]},
        "BpvenPayAdd3": {"type": ["string", "null"]},
        "BpvenPayRegionCode": {"type": ["string", "null"]},
        "BpvenPayRegionName": {"type": ["string", "null"]},
        "BpvenPayCountry": {"type": ["string", "null"]},
        "BpvenPayPostalCode": {"type": ["string", "null"]},
        "BpvenPayContactName": {"type": ["string", "null"]},
        "BpvenPayPhone": {"type": ["string", "null"]},
        "BpvenPayFax": {"type": ["string", "null"]},
        "BpvenPayEmail": {"type": ["string", "null"]},
        "BpvenWebSite": {"type": ["string", "null"]},
        "BpvenBuyCode": {"type": ["string", "null"]},
        "BpvenClassCode": {"type": ["string", "null"]},
        "BpvenClassName": {"type": ["string", "null"]},
        "BpvenStatusCode": {"type": ["string", "null"]},
        "BpvenPrefCode": {"type": ["string", "null"]},
        "BpvenPrefName": {"type": ["string", "null"]},
        "BpvenTermCode": {"type": ["string", "null"]},
        "BpvenTermName": {"type": ["string", "null"]},
        "Bpven1099Code": {"type": ["string", "null"]},
        "Bpven1099Name": {"type": ["string", "null"]},
        "BpvenAltAddCode": {"type": ["string", "null"]},
        "BpvenAltAddName": {"type": ["string", "null"]},
        "BpvenShpinstDesc": {"type": ["string", "null"]},
        "BpvenActiveFlag": {"type": ["string", "null"]},
        "Bpven5018RepFlag": {"type": ["string", "null"]},
        "BpvenOneTimeFlag": {"type": ["string", "null"]},
        "BpvenUseApctrlComplFlag": {"type": ["string", "null"]},
        "BpvenSpecialTermsFlag": {"type": ["string", "null"]},
        "BpvenOrdAdd1": {"type": ["string", "null"]},
        "BpvenOrdAdd2": {"type": ["string", "null"]},
        "BpvenOrdAdd3": {"type": ["string", "null"]},
        "BpvenOrdRegionCode": {"type": ["string", "null"]},
        "BpvenOrdCountry": {"type": ["string", "null"]},
        "BpvenOrdPostalCode": {"type": ["string", "null"]},
        "BpvenOrdContactName": {"type": ["string", "null"]},
        "BpvenOrdPhone": {"type": ["string", "null"]},
        "BpvenOrdFax": {"type": ["string", "null"]},
        "BpvenOrdEmail": {"type": ["string", "null"]},
        "BpvenCurrCode": {"type": ["string", "null"]},
        "BpvenInvSerCode": {"type": ["string", "null"]},
        "BpvenDistTypeCode": {"type": ["string", "null"]},
        "BpvenHldbkPc": {"type": ["number", "null"]},
        "BpvenAllowTranFlag": {"type": ["string", "null"]},
        "BpvenCheckMergeFlag": {"type": ["string", "null"]},
        "BpvenDiscreteChqFlag": {"type": ["string", "null"]},
        "BpvenPrenoteFlag": {"type": ["string", "null"]},
        "BpvenTppayCode": {"type": ["string", "null"]},
        "BpvenDefaultPayCode": {"type": ["string", "null"]},
        "BpvenEftFlag": {"type": ["string", "null"]},
        "BpvenEftEmail": {"type": ["string", "null"]},
        "BpvenPrefContactMth": {"type": ["string", "null"]},
        "BpvenEmpNo": {"type": ["string", "null"]},
        "BpvenBankCode": {"type": ["string", "null"]},
        "BpvenBankAccNum1": {"type": ["string", "null"]},
        "BpvenBankAccNum2": {"type": ["string", "null"]},
        "BpvenBankAccNum3": {"type": ["string", "null"]},
        "BpvenPaymodeId": {"type": ["string", "null"]},
        "BpvenIbanNum": {"type": ["string", "null"]},
        "BpvenSwiftBicCode": {"type": ["string", "null"]},
        "BpvenApDeptCode": {"type": ["string", "null"]},
        "BpvenApAccCode": {"type": ["string", "null"]},
        "BpvenCashDeptCode": {"type": ["string", "null"]},
        "BpvenCashAccCode": {"type": ["string", "null"]},
        "BpvenExpDeptCode": {"type": ["string", "null"]},
        "BpvenExpAccCode": {"type": ["string", "null"]},
        "BpvenPpeDeptCode": {"type": ["string", "null"]},
        "BpvenPpeAccCode": {"type": ["string", "null"]},
        "BpvenDiscDeptCode": {"type": ["string", "null"]},
        "BpvenDiscAccCode": {"type": ["string", "null"]},
        "BpvenHldbkDeptCode": {"type": ["string", "null"]},
        "BpvenHldbkAccCode": {"type": ["string", "null"]},
        "BpvenTax1Code": {"type": ["string", "null"]},
        "BpvenTaxlic1": {"type": ["string", "null"]},
        "BpvenTax2Code": {"type": ["string", "null"]},
        "BpvenTaxlic2": {"type": ["string", "null"]},
        "BpvenTax3Code": {"type": ["string", "null"]},
        "BpvenTaxlic3": {"type": ["string", "null"]},
        "BpvenTax4Code": {"type": ["string", "null"]},
        "BpvenTaxlic4": {"type": ["string", "null"]},
        "BpvenTax5Code": {"type": ["string", "null"]},
        "BpvenTaxlic5": {"type": ["string", "null"]},
        "BpvenVUuid": {"type": ["string", "null"]},
        "BpvenIuCreateDate": {"type": ["string", "null"], "format": "date-time"},
        "BpvenIuUpdateDate": {"type": ["string", "null"], "format": "date-time"},
        "BpIuCreateDate": {"type": ["string", "null"], "format": "date-time"},
        "BpIuUpdateDate": {"type": ["string", "null"], "format": "date-time"},
        "BpvenEftPaymentType": {"type": ["string", "null"]},
        "links": {
            "type": ["array", "null"],
            "items": {
                "type": "object",
                "properties": {
                    "rel": {"type": ["string", "null"]},
                    "href": {"type": ["string", "null"]},
                    "name": {"type": ["string", "null"]},
                    "kind": {"type": ["string", "null"]},
                },
            },
        },
    },
}
